Repository openvanilla/McBopomofo, pull requests merged in 2025-03, with the labels that each got.

#621 Create temp dir instead of letting unzip do it
  Source/Installer/ArchiveUtil.swift
Labels: Review effort 2/5

#622 Show fatal error if no installable package found
  Source/Installer/AppDelegate.swift
  Source/Installer/en.lproj/Localizable.strings
  Source/Installer/zh-Hant.lproj/Localizable.strings
Labels: Review effort 2/5

#623 Release 2.9.2
  Source/Installer/Installer-Info.plist
  Source/McBopomofo-Info.plist
Labels: Review effort 1/5

#624 Experimental: Repeated punctuation keys to select next candidate without the candidate window
  Source/Base.lproj/preferences.xib
  Source/KeyHandler.mm
  Source/Preferences.swift
  Source/zh-Hant.lproj/preferences.xib
Labels: Review effort 2/5

#628 Python code refactoring: use argparse in cook.py
  Source/Data/Makefile
  Source/Data/bin/cook.py
Labels: Review effort 3/5
